In [41]:
import pickle
import pandas as pd
import numpy as np

with open('data.pkl', 'rb') as f:
    data = pickle.load(f)

In [42]:
fields = list(data.keys())
print(fields)

['COORD', 'NT11', 'S']

In [43]:
def iterate_and_extract(data, extract_function):
    results = set()
    for df in data:
            result = extract_function(df)
            results.update(result)
    results = list(results)
    results.sort()
    return results

In [ ]:
for field in fields:

    extract_function  = lambda df: df.columns
    dofs = iterate_and_extract(data[field], extract_function)
    print(dofs)

    extract_function  = lambda df: df.index.values
    times = iterate_and_extract(data[field], extract_function)
    print(times)

[('COORD', 'COOR1', 'PART-1-1', 1), ('COORD', 'COOR1', 'PART-1-1', 2), ('COORD', 'COOR1', 'PART-1-1', 3), ('COORD', 'COOR1', 'PART-1-1', 4), ('COORD', 'COOR1', 'PART-1-1', 5), ('COORD', 'COOR1', 'PART-1-1', 6), ('COORD', 'COOR1', 'PART-1-1', 7), ('COORD', 'COOR1', 'PART-1-1', 8), ('COORD', 'COOR1', 'PART-1-1', 9), ('COORD', 'COOR1', 'PART-1-1', 10), ('COORD', 'COOR1', 'PART-1-1', 11), ('COORD', 'COOR1', 'PART-1-1', 12), ('COORD', 'COOR1', 'PART-1-1', 13), ('COORD', 'COOR1', 'PART-1-1', 14), ('COORD', 'COOR1', 'PART-1-1', 15), ('COORD', 'COOR1', 'PART-1-1', 16), ('COORD', 'COOR1', 'PART-1-1', 17), ('COORD', 'COOR1', 'PART-1-1', 18), ('COORD', 'COOR1', 'PART-1-1', 19), ('COORD', 'COOR1', 'PART-1-1', 20), ('COORD', 'COOR1', 'PART-1-1', 21), ('COORD', 'COOR1', 'PART-1-1', 22), ('COORD', 'COOR1', 'PART-1-1', 23), ('COORD', 'COOR1', 'PART-1-1', 24), ('COORD', 'COOR1', 'PART-1-1', 25), ('COORD', 'COOR1', 'PART-1-1', 26), ('COORD', 'COOR1', 'PART-1-1', 27), ('COORD', 'COOR1', 'PART-1-1', 28), ('COORD', 'COOR1', 'PART-1-1', 29), ('COORD', 'COOR1', 'PART-1-1', 30), ('COORD', 'COOR1', 'PART-1-1', 31), ('COORD', 'COOR1', 'PART-1-1', 32), ('COORD', 'COOR1', 'PART-1-1', 33), ('COORD', 'COOR1', 'PART-1-1', 34), ('COORD', 'COOR1', 'PART-1-1', 35), ('COORD', 'COOR1', 'PART-1-1', 36), ('COORD', 'COOR1', 'PART-1-1', 37), ('COORD', 'COOR1', 'PART-1-1', 38), ('COORD', 'COOR1', 'PART-1-1', 39), ('COORD', 'COOR1', 'PART-1-1', 40), ('COORD', 'COOR1', 'PART-1-1', 41), ('COORD', 'COOR1', 'PART-1-1', 42), ('COORD', 'COOR1', 'PART-1-1', 43), ('COORD', 'COOR1', 'PART-1-1', 44), ('COORD', 'COOR1', 'PART-1-1', 45), ('COORD', 'COOR1', 'PART-1-1', 46), ('COORD', 'COOR1', 'PART-1-1', 47), ('COORD', 'COOR1', 'PART-1-1', 48), ('COORD', 'COOR1', 'PART-1-1', 49), ('COORD', 'COOR1', 'PART-1-1', 50), ('COORD', 'COOR1', 'PART-1-1', 51), ('COORD', 'COOR1', 'PART-1-1', 52), ('COORD', 'COOR1', 'PART-1-1', 53), ('COORD', 'COOR1', 'PART-1-1', 54), ('COORD', 'COOR1', 'PART-1-1', 55), ('COORD', 'COOR1', 'PART-1-1', 56), ('COORD', 'COOR1', 'PART-1-1', 57), ('COORD', 'COOR1', 'PART-1-1', 58), ('COORD', 'COOR1', 'PART-1-1', 59), ('COORD', 'COOR1', 'PART-1-1', 60), ('COORD', 'COOR1', 'PART-1-1', 61), ('COORD', 'COOR1', 'PART-1-1', 62), ('COORD', 'COOR1', 'PART-1-1', 63), ('COORD', 'COOR1', 'PART-1-1', 64), ('COORD', 'COOR1', 'PART-1-1', 65), ('COORD', 'COOR1', 'PART-1-1', 66), ('COORD', 'COOR1', 'PART-1-1', 67), ('COORD', 'COOR1', 'PART-1-1', 68), ('COORD', 'COOR1', 'PART-1-1', 69), ('COORD', 'COOR1', 'PART-1-1', 70), ('COORD', 'COOR1', 'PART-1-1', 71), ('COORD', 'COOR1', 'PART-1-1', 72), ('COORD', 'COOR1', 'PART-1-1', 73), ('COORD', 'COOR1', 'PART-1-1', 74), ('COORD', 'COOR1', 'PART-1-1', 75), ('COORD', 'COOR1', 'PART-1-1', 76), ('COORD', 'COOR1', 'PART-1-1', 77), ('COORD', 'COOR1', 'PART-1-1', 78), ('COORD', 'COOR1', 'PART-1-1', 79), ('COORD', 'COOR1', 'PART-1-1', 80), ('COORD', 'COOR1', 'PART-1-1', 81), ('COORD', 'COOR1', 'PART-1-1', 82), ('COORD', 'COOR1', 'PART-1-1', 83), ('COORD', 'COOR1', 'PART-1-1', 84), ('COORD', 'COOR1', 'PART-1-1', 85), ('COORD', 'COOR1', 'PART-1-1', 86), ('COORD', 'COOR1', 'PART-1-1', 87), ('COORD', 'COOR1', 'PART-1-1', 88), ('COORD', 'COOR1', 'PART-1-1', 89), ('COORD', 'COOR1', 'PART-1-1', 90), ('COORD', 'COOR1', 'PART-1-1', 91), ('COORD', 'COOR1', 'PART-1-1', 92), ('COORD', 'COOR1', 'PART-1-1', 93), ('COORD', 'COOR1', 'PART-1-1', 94), ('COORD', 'COOR1', 'PART-1-1', 95), ('COORD', 'COOR1', 'PART-1-1', 96), ('COORD', 'COOR1', 'PART-1-1', 97), ('COORD', 'COOR1', 'PART-1-1', 98), ('COORD', 'COOR1', 'PART-1-1', 99), ('COORD', 'COOR1', 'PART-1-1', 100), ('COORD', 'COOR1', 'PART-1-1', 101), ('COORD', 'COOR1', 'PART-1-1', 102), ('COORD', 'COOR1', 'PART-1-1', 103), ('COORD', 'COOR1', 'PART-1-1', 104), ('COORD', 'COOR1', 'PART-1-1', 105), ('COORD', 'COOR1', 'PART-1-1', 106), ('COORD', 'COOR1', 'PART-1-1', 107), ('COORD', 'COOR1', 'PART-1-1', 108), ('COORD', 'COOR1', 'PART-1-1', 109), ('COORD', 'COOR1', 'PART-1-1', 110), ('COORD', 'COOR1', 'PART-1-1', 111), ('COORD', 'COOR1', 'PART-1-1', 112), ('COORD', 'COOR1', 'PART-1-1', 113), ('COORD', 'COOR1', 'PART-1-1', 114), ('COORD', 'COOR1', 'PART-1-1', 115), ('COORD', 'COOR1', 'PART-1-1', 116), ('COORD', 'COOR1', 'PART-1-1', 117), ('COORD', 'COOR1', 'PART-1-1', 118), ('COORD', 'COOR1', 'PART-1-1', 119), ('COORD', 'COOR1', 'PART-1-1', 120), ('COORD', 'COOR1', 'PART-1-1', 121), ('COORD', 'COOR1', 'PART-1-1', 122), ('COORD', 'COOR1', 'PART-1-1', 123), ('COORD', 'COOR1', 'PART-1-1', 124), ('COORD', 'COOR1', 'PART-1-1', 125), ('COORD', 'COOR1', 'PART-1-1', 126), ('COORD', 'COOR1', 'PART-1-1', 127), ('COORD', 'COOR1', 'PART-1-1', 128), ('COORD', 'COOR1', 'PART-1-1', 129), ('COORD', 'COOR1', 'PART-1-1', 130), ('COORD', 'COOR1', 'PART-1-1', 131), ('COORD', 'COOR1', 'PART-1-1', 132), ('COORD', 'COOR1', 'PART-1-1', 133), ('COORD', 'COOR1', 'PART-1-1', 134), ('COORD', 'COOR1', 'PART-1-1', 135), ('COORD', 'COOR1', 'PART-1-1', 136), ('COORD', 'COOR1', 'PART-1-1', 137), ('COORD', 'COOR1', 'PART-1-1', 138), ('COORD', 'COOR1', 'PART-1-1', 139), ('COORD', 'COOR1', 'PART-1-1', 140), ('COORD', 'COOR1', 'PART-1-1', 141), ('COORD', 'COOR1', 'PART-1-1', 142), ('COORD', 'COOR1', 'PART-1-1', 143), ('COORD', 'COOR1', 'PART-1-1', 144), ('COORD', 'COOR1', 'PART-1-1', 145), ('COORD', 'COOR1', 'PART-1-1', 146), ('COORD', 'COOR1', 'PART-1-1', 147), ('COORD', 'COOR1', 'PART-1-1', 148), ('COORD', 'COOR1', 'PART-1-1', 149), ('COORD', 'COOR1', 'PART-1-1', 150), ('COORD', 'COOR1', 'PART-1-1', 151), ('COORD', 'COOR1', 'PART-1-1', 152), ('COORD', 'COOR1', 'PART-1-1', 153), ('COORD', 'COOR1', 'PART-1-1', 154), ('COORD', 'COOR1', 'PART-1-1', 155), ('COORD', 'COOR1', 'PART-1-1', 156), ('COORD', 'COOR1', 'PART-1-1', 157), ('COORD', 'COOR1', 'PART-1-1', 158), ('COORD', 'COOR1', 'PART-1-1', 159), ('COORD', 'COOR1', 'PART-1-1', 160), ('COORD', 'COOR1', 'PART-1-1', 161), ('COORD', 'COOR1', 'PART-1-1', 162), ('COORD', 'COOR1', 'PART-1-1', 163), ('COORD', 'COOR1', 'PART-1-1', 164), ('COORD', 'COOR1', 'PART-1-1', 165), ('COORD', 'COOR1', 'PART-1-1', 166), ('COORD', 'COOR1', 'PART-1-1', 167), ('COORD', 'COOR1', 'PART-1-1', 168), ('COORD', 'COOR1', 'PART-1-1', 169), ('COORD', 'COOR1', 'PART-1-1', 170), ('COORD', 'COOR1', 'PART-1-1', 171), ('COORD', 'COOR1', 'PART-1-1', 172), ('COORD', 'COOR1', 'PART-1-1', 173), ('COORD', 'COOR1', 'PART-1-1', 174), ('COORD', 'COOR1', 'PART-1-1', 175), ('COORD', 'COOR1', 'PART-1-1', 176), ('COORD', 'COOR1', 'PART-1-1', 177), ('COORD', 'COOR1', 'PART-1-1', 178), ('COORD', 'COOR1', 'PART-1-1', 179), ('COORD', 'COOR1', 'PART-1-1', 180), ('COORD', 'COOR1', 'PART-1-1', 181), ('COORD', 'COOR1', 'PART-1-1', 182), ('COORD', 'COOR1', 'PART-1-1', 183), ('COORD', 'COOR1', 'PART-1-1', 184), ('COORD', 'COOR1', 'PART-1-1', 185), ('COORD', 'COOR1', 'PART-1-1', 186), ('COORD', 'COOR1', 'PART-1-1', 187), ('COORD', 'COOR1', 'PART-1-1', 188), ('COORD', 'COOR1', 'PART-1-1', 189), ('COORD', 'COOR1', 'PART-1-1', 190), ('COORD', 'COOR1', 'PART-1-1', 191), ('COORD', 'COOR1', 'PART-1-1', 192), ('COORD', 'COOR1', 'PART-1-1', 193), ('COORD', 'COOR1', 'PART-1-1', 194), ('COORD', 'COOR1', 'PART-1-1', 195), ('COORD', 'COOR1', 'PART-1-1', 196), ('COORD', 'COOR1', 'PART-1-1', 197), ('COORD', 'COOR1', 'PART-1-1', 198), ('COORD', 'COOR1', 'PART-1-1', 199), ('COORD', 'COOR1', 'PART-1-1', 200), ('COORD', 'COOR1', 'PART-1-2', 1), ('COORD', 'COOR1', 'PART-1-2', 2), ('COORD', 'COOR1', 'PART-1-2', 3), ('COORD', 'COOR1', 'PART-1-2', 4), ('COORD', 'COOR1', 'PART-1-2', 5), ('COORD', 'COOR1', 'PART-1-2', 6), ('COORD', 'COOR1', 'PART-1-2', 7), ('COORD', 'COOR1', 'PART-1-2', 8), ('COORD', 'COOR1', 'PART-1-2', 9), ('COORD', 'COOR1', 'PART-1-2', 10), ('COORD', 'COOR1', 'PART-1-2', 11), ('COORD', 'COOR1', 'PART-1-2', 12), ('COORD', 'COOR1', 'PART-1-2', 13), ('COORD', 'COOR1', 'PART-1-2', 14), ('COORD', 'COOR1', 'PART-1-2', 15), ('COORD', 'COOR1', 'PART-1-2', 16), ('COORD', 'COOR1', 'PART-1-2', 17), ('COORD', 'COOR1', 'PART-1-2', 18), ('COORD', 'COOR1', 'PART-1-2', 19), ('COORD', 'COOR1', 'PART-1-2', 20), ('COORD', 'COOR1', 'PART-1-2', 21), ('COORD', 'COOR1', 'PART-1-2', 22), ('COORD', 'COOR1', 'PART-1-2', 23), ('COORD', 'COOR1', 'PART-1-2', 24), ('COORD', 'COOR1', 'PART-1-2', 25), ('COORD', 'COOR1', 'PART-1-2', 26), ('COORD', 'COOR1', 'PART-1-2', 27), ('COORD', 'COOR1', 'PART-1-2', 28), ('COORD', 'COOR1', 'PART-1-2', 29), ('COORD', 'COOR1', 'PART-1-2', 30), ('COORD', 'COOR1', 'PART-1-2', 31), ('COORD', 'COOR1', 'PART-1-2', 32), ('COORD', 'COOR1', 'PART-1-2', 33), ('COORD', 'COOR1', 'PART-1-2', 34), ('COORD', 'COOR1', 'PART-1-2', 35), ('COORD', 'COOR1', 'PART-1-2', 36), ('COORD', 'COOR1', 'PART-1-2', 37), ('COORD', 'COOR1', 'PART-1-2', 38), ('COORD', 'COOR1', 'PART-1-2', 39), ('COORD', 'COOR1', 'PART-1-2', 40), ('COORD', 'COOR1', 'PART-1-2', 41), ('COORD', 'COOR1', 'PART-1-2', 42), ('COORD', 'COOR1', 'PART-1-2', 43), ('COORD', 'COOR1', 'PART-1-2', 44), ('COORD', 'COOR1', 'PART-1-2', 45), ('COORD', 'COOR1', 'PART-1-2', 46), ('COORD', 'COOR1', 'PART-1-2', 47), ('COORD', 'COOR1', 'PART-1-2', 48), ('COORD', 'COOR1', 'PART-1-2', 49), ('COORD', 'COOR1', 'PART-1-2', 50), ('COORD', 'COOR1', 'PART-1-2', 51), ('COORD', 'COOR1', 'PART-1-2', 52), ('COORD', 'COOR1', 'PART-1-2', 53), ('COORD', 'COOR1', 'PART-1-2', 54), ('COORD', 'COOR1', 'PART-1-2', 55), ('COORD', 'COOR1', 'PART-1-2', 56), ('COORD', 'COOR1', 'PART-1-2', 57), ('COORD', 'COOR1', 'PART-1-2', 58), ('COORD', 'COOR1', 'PART-1-2', 59), ('COORD', 'COOR1', 'PART-1-2', 60), ('COORD', 'COOR1', 'PART-1-2', 61), ('COORD', 'COOR1', 'PART-1-2', 62), ('COORD', 'COOR1', 'PART-1-2', 63), ('COORD', 'COOR1', 'PART-1-2', 64), ('COORD', 'COOR1', 'PART-1-2', 65), ('COORD', 'COOR1', 'PART-1-2', 66), ('COORD', 'COOR1', 'PART-1-2', 67), ('COORD', 'COOR1', 'PART-1-2', 68), ('COORD', 'COOR1', 'PART-1-2', 69), ('COORD', 'COOR1', 'PART-1-2', 70), ('COORD', 'COOR1', 'PART-1-2', 71), ('COORD', 'COOR1', 'PART-1-2', 72), ('COORD', 'COOR1', 'PART-1-2', 73), ('COORD', 'COOR1', 'PART-1-2', 74), ('COORD', 'COOR1', 'PART-1-2', 75), ('COORD', 'COOR1', 'PART-1-2', 76), ('COORD', 'COOR1', 'PART-1-2', 77), ('COORD', 'COOR1', 'PART-1-2', 78), ('COORD', 'COOR1', 'PART-1-2', 79), ('COORD', 'COOR1', 'PART-1-2', 80), ('COORD', 'COOR1', 'PART-1-2', 81), ('COORD', 'COOR1', 'PART-1-2', 82), ('COORD', 'COOR1', 'PART-1-2', 83), ('COORD', 'COOR1', 'PART-1-2', 84), ('COORD', 'COOR1', 'PART-1-2', 85), ('COORD', 'COOR1', 'PART-1-2', 86), ('COORD', 'COOR1', 'PART-1-2', 87), ('COORD', 'COOR1', 'PART-1-2', 88), ('COORD', 'COOR1', 'PART-1-2', 89), ('COORD', 'COOR1', 'PART-1-2', 90), ('COORD', 'COOR1', 'PART-1-2', 91), ('COORD', 'COOR1', 'PART-1-2', 92), ('COORD', 'COOR1', 'PART-1-2', 93), ('COORD', 'COOR1', 'PART-1-2', 94), ('COORD', 'COOR1', 'PART-1-2', 95), ('COORD', 'COOR1', 'PART-1-2', 96), ('COORD', 'COOR1', 'PART-1-2', 97), ('COORD', 'COOR1', 'PART-1-2', 98), ('COORD', 'COOR1', 'PART-1-2', 99), ('COORD', 'COOR1', 'PART-1-2', 100), ('COORD', 'COOR1', 'PART-1-2', 101), ('COORD', 'COOR1', 'PART-1-2', 102), ('COORD', 'COOR1', 'PART-1-2', 103), ('COORD', 'COOR1', 'PART-1-2', 104), ('COORD', 'COOR1', 'PART-1-2', 105), ('COORD', 'COOR1', 'PART-1-2', 106), ('COORD', 'COOR1', 'PART-1-2', 107), ('COORD', 'COOR1', 'PART-1-2', 108), ('COORD', 'COOR1', 'PART-1-2', 109), ('COORD', 'COOR1', 'PART-1-2', 110), ('COORD', 'COOR1', 'PART-1-2', 111), ('COORD', 'COOR1', 'PART-1-2', 112), ('COORD', 'COOR1', 'PART-1-2', 113), ('COORD', 'COOR1', 'PART-1-2', 114), ('COORD', 'COOR1', 'PART-1-2', 115), ('COORD', 'COOR1', 'PART-1-2', 116), ('COORD', 'COOR1', 'PART-1-2', 117), ('COORD', 'COOR1', 'PART-1-2', 118), ('COORD', 'COOR1', 'PART-1-2', 119), ('COORD', 'COOR1', 'PART-1-2', 120), ('COORD', 'COOR1', 'PART-1-2', 121), ('COORD', 'COOR1', 'PART-1-2', 122), ('COORD', 'COOR1', 'PART-1-2', 123), ('COORD', 'COOR1', 'PART-1-2', 124), ('COORD', 'COOR1', 'PART-1-2', 125), ('COORD', 'COOR1', 'PART-1-2', 126), ('COORD', 'COOR1', 'PART-1-2', 127), ('COORD', 'COOR1', 'PART-1-2', 128), ('COORD', 'COOR1', 'PART-1-2', 129), ('COORD', 'COOR1', 'PART-1-2', 130), ('COORD', 'COOR1', 'PART-1-2', 131), ('COORD', 'COOR1', 'PART-1-2', 132), ('COORD', 'COOR1', 'PART-1-2', 133), ('COORD', 'COOR1', 'PART-1-2', 134), ('COORD', 'COOR1', 'PART-1-2', 135), ('COORD', 'COOR1', 'PART-1-2', 136), ('COORD', 'COOR1', 'PART-1-2', 137), ('COORD', 'COOR1', 'PART-1-2', 138), ('COORD', 'COOR1', 'PART-1-2', 139), ('COORD', 'COOR1', 'PART-1-2', 140), ('COORD', 'COOR1', 'PART-1-2', 141), ('COORD', 'COOR1', 'PART-1-2', 142), ('COORD', 'COOR1', 'PART-1-2', 143), ('COORD', 'COOR1', 'PART-1-2', 144), ('COORD', 'COOR1', 'PART-1-2', 145), ('COORD', 'COOR1', 'PART-1-2', 146), ('COORD', 'COOR1', 'PART-1-2', 147), ('COORD', 'COOR1', 'PART-1-2', 148), ('COORD', 'COOR1', 'PART-1-2', 149), ('COORD', 'COOR1', 'PART-1-2', 150), ('COORD', 'COOR1', 'PART-1-2', 151), ('COORD', 'COOR1', 'PART-1-2', 152), ('COORD', 'COOR1', 'PART-1-2', 153), ('COORD', 'COOR1', 'PART-1-2', 154), ('COORD', 'COOR1', 'PART-1-2', 155), ('COORD', 'COOR1', 'PART-1-2', 156), ('COORD', 'COOR1', 'PART-1-2', 157), ('COORD', 'COOR1', 'PART-1-2', 158), ('COORD', 'COOR1', 'PART-1-2', 159), ('COORD', 'COOR1', 'PART-1-2', 160), ('COORD', 'COOR1', 'PART-1-2', 161), ('COORD', 'COOR1', 'PART-1-2', 162), ('COORD', 'COOR1', 'PART-1-2', 163), ('COORD', 'COOR1', 'PART-1-2', 164), ('COORD', 'COOR1', 'PART-1-2', 165), ('COORD', 'COOR1', 'PART-1-2', 166), ('COORD', 'COOR1', 'PART-1-2', 167), ('COORD', 'COOR1', 'PART-1-2', 168), ('COORD', 'COOR1', 'PART-1-2', 169), ('COORD', 'COOR1', 'PART-1-2', 170), ('COORD', 'COOR1', 'PART-1-2', 171), ('COORD', 'COOR1', 'PART-1-2', 172), ('COORD', 'COOR1', 'PART-1-2', 173), ('COORD', 'COOR1', 'PART-1-2', 174), ('COORD', 'COOR1', 'PART-1-2', 175), ('COORD', 'COOR1', 'PART-1-2', 176), ('COORD', 'COOR1', 'PART-1-2', 177), ('COORD', 'COOR1', 'PART-1-2', 178), ('COORD', 'COOR1', 'PART-1-2', 179), ('COORD', 'COOR1', 'PART-1-2', 180), ('COORD', 'COOR1', 'PART-1-2', 181), ('COORD', 'COOR1', 'PART-1-2', 182), ('COORD', 'COOR1', 'PART-1-2', 183), ('COORD', 'COOR1', 'PART-1-2', 184), ('COORD', 'COOR1', 'PART-1-2', 185), ('COORD', 'COOR1', 'PART-1-2', 186), ('COORD', 'COOR1', 'PART-1-2', 187), ('COORD', 'COOR1', 'PART-1-2', 188), ('COORD', 'COOR1', 'PART-1-2', 189), ('COORD', 'COOR1', 'PART-1-2', 190), ('COORD', 'COOR1', 'PART-1-2', 191), ('COORD', 'COOR1', 'PART-1-2', 192), ('COORD', 'COOR1', 'PART-1-2', 193), ('COORD', 'COOR1', 'PART-1-2', 194), ('COORD', 'COOR1', 'PART-1-2', 195), ('COORD', 'COOR1', 'PART-1-2', 196), ('COORD', 'COOR1', 'PART-1-2', 197), ('COORD', 'COOR1', 'PART-1-2', 198), ('COORD', 'COOR1', 'PART-1-2', 199), ('COORD', 'COOR1', 'PART-1-2', 200), ('COORD', 'COOR2', 'PART-1-1', 1), ('COORD', 'COOR2', 'PART-1-1', 2), ('COORD', 'COOR2', 'PART-1-1', 3), ('COORD', 'COOR2', 'PART-1-1', 4), ('COORD', 'COOR2', 'PART-1-1', 5), ('COORD', 'COOR2', 'PART-1-1', 6), ('COORD', 'COOR2', 'PART-1-1', 7), ('COORD', 'COOR2', 'PART-1-1', 8), ('COORD', 'COOR2', 'PART-1-1', 9), ('COORD', 'COOR2', 'PART-1-1', 10), ('COORD', 'COOR2', 'PART-1-1', 11), ('COORD', 'COOR2', 'PART-1-1', 12), ('COORD', 'COOR2', 'PART-1-1', 13), ('COORD', 'COOR2', 'PART-1-1', 14), ('COORD', 'COOR2', 'PART-1-1', 15), ('COORD', 'COOR2', 'PART-1-1', 16), ('COORD', 'COOR2', 'PART-1-1', 17), ('COORD', 'COOR2', 'PART-1-1', 18), ('COORD', 'COOR2', 'PART-1-1', 19), ('COORD', 'COOR2', 'PART-1-1', 20), ('COORD', 'COOR2', 'PART-1-1', 21), ('COORD', 'COOR2', 'PART-1-1', 22), ('COORD', 'COOR2', 'PART-1-1', 23), ('COORD', 'COOR2', 'PART-1-1', 24), ('COORD', 'COOR2', 'PART-1-1', 25), ('COORD', 'COOR2', 'PART-1-1', 26), ('COORD', 'COOR2', 'PART-1-1', 27), ('COORD', 'COOR2', 'PART-1-1', 28), ('COORD', 'COOR2', 'PART-1-1', 29), ('COORD', 'COOR2', 'PART-1-1', 30), ('COORD', 'COOR2', 'PART-1-1', 31), ('COORD', 'COOR2', 'PART-1-1', 32), ('COORD', 'COOR2', 'PART-1-1', 33), ('COORD', 'COOR2', 'PART-1-1', 34), ('COORD', 'COOR2', 'PART-1-1', 35), ('COORD', 'COOR2', 'PART-1-1', 36), ('COORD', 'COOR2', 'PART-1-1', 37), ('COORD', 'COOR2', 'PART-1-1', 38), ('COORD', 'COOR2', 'PART-1-1', 39), ('COORD', 'COOR2', 'PART-1-1', 40), ('COORD', 'COOR2', 'PART-1-1', 41), ('COORD', 'COOR2', 'PART-1-1', 42), ('COORD', 'COOR2', 'PART-1-1', 43), ('COORD', 'COOR2', 'PART-1-1', 44), ('COORD', 'COOR2', 'PART-1-1', 45), ('COORD', 'COOR2', 'PART-1-1', 46), ('COORD', 'COOR2', 'PART-1-1', 47), ('COORD', 'COOR2', 'PART-1-1', 48), ('COORD', 'COOR2', 'PART-1-1', 49), ('COORD', 'COOR2', 'PART-1-1', 50), ('COORD', 'COOR2', 'PART-1-1', 51), ('COORD', 'COOR2', 'PART-1-1', 52), ('COORD', 'COOR2', 'PART-1-1', 53), ('COORD', 'COOR2', 'PART-1-1', 54), ('COORD', 'COOR2', 'PART-1-1', 55), ('COORD', 'COOR2', 'PART-1-1', 56), ('COORD', 'COOR2', 'PART-1-1', 57), ('COORD', 'COOR2', 'PART-1-1', 58), ('COORD', 'COOR2', 'PART-1-1', 59), ('COORD', 'COOR2', 'PART-1-1', 60), ('COORD', 'COOR2', 'PART-1-1', 61), ('COORD', 'COOR2', 'PART-1-1', 62), ('COORD', 'COOR2', 'PART-1-1', 63), ('COORD', 'COOR2', 'PART-1-1', 64), ('COORD', 'COOR2', 'PART-1-1', 65), ('COORD', 'COOR2', 'PART-1-1', 66), ('COORD', 'COOR2', 'PART-1-1', 67), ('COORD', 'COOR2', 'PART-1-1', 68), ('COORD', 'COOR2', 'PART-1-1', 69), ('COORD', 'COOR2', 'PART-1-1', 70), ('COORD', 'COOR2', 'PART-1-1', 71), ('COORD', 'COOR2', 'PART-1-1', 72), ('COORD', 'COOR2', 'PART-1-1', 73), ('COORD', 'COOR2', 'PART-1-1', 74), ('COORD', 'COOR2', 'PART-1-1', 75), ('COORD', 'COOR2', 'PART-1-1', 76), ('COORD', 'COOR2', 'PART-1-1', 77), ('COORD', 'COOR2', 'PART-1-1', 78), ('COORD', 'COOR2', 'PART-1-1', 79), ('COORD', 'COOR2', 'PART-1-1', 80), ('COORD', 'COOR2', 'PART-1-1', 81), ('COORD', 'COOR2', 'PART-1-1', 82), ('COORD', 'COOR2', 'PART-1-1', 83), ('COORD', 'COOR2', 'PART-1-1', 84), ('COORD', 'COOR2', 'PART-1-1', 85), ('COORD', 'COOR2', 'PART-1-1', 86), ('COORD', 'COOR2', 'PART-1-1', 87), ('COORD', 'COOR2', 'PART-1-1', 88), ('COORD', 'COOR2', 'PART-1-1', 89), ('COORD', 'COOR2', 'PART-1-1', 90), ('COORD', 'COOR2', 'PART-1-1', 91), ('COORD', 'COOR2', 'PART-1-1', 92), ('COORD', 'COOR2', 'PART-1-1', 93), ('COORD', 'COOR2', 'PART-1-1', 94), ('COORD', 'COOR2', 'PART-1-1', 95), ('COORD', 'COOR2', 'PART-1-1', 96), ('COORD', 'COOR2', 'PART-1-1', 97), ('COORD', 'COOR2', 'PART-1-1', 98), ('COORD', 'COOR2', 'PART-1-1', 99), ('COORD', 'COOR2', 'PART-1-1', 100), ('COORD', 'COOR2', 'PART-1-1', 101), ('COORD', 'COOR2', 'PART-1-1', 102), ('COORD', 'COOR2', 'PART-1-1', 103), ('COORD', 'COOR2', 'PART-1-1', 104), ('COORD', 'COOR2', 'PART-1-1', 105), ('COORD', 'COOR2', 'PART-1-1', 106), ('COORD', 'COOR2', 'PART-1-1', 107), ('COORD', 'COOR2', 'PART-1-1', 108), ('COORD', 'COOR2', 'PART-1-1', 109), ('COORD', 'COOR2', 'PART-1-1', 110), ('COORD', 'COOR2', 'PART-1-1', 111), ('COORD', 'COOR2', 'PART-1-1', 112), ('COORD', 'COOR2', 'PART-1-1', 113), ('COORD', 'COOR2', 'PART-1-1', 114), ('COORD', 'COOR2', 'PART-1-1', 115), ('COORD', 'COOR2', 'PART-1-1', 116), ('COORD', 'COOR2', 'PART-1-1', 117), ('COORD', 'COOR2', 'PART-1-1', 118), ('COORD', 'COOR2', 'PART-1-1', 119), ('COORD', 'COOR2', 'PART-1-1', 120), ('COORD', 'COOR2', 'PART-1-1', 121), ('COORD', 'COOR2', 'PART-1-1', 122), ('COORD', 'COOR2', 'PART-1-1', 123), ('COORD', 'COOR2', 'PART-1-1', 124), ('COORD', 'COOR2', 'PART-1-1', 125), ('COORD', 'COOR2', 'PART-1-1', 126), ('COORD', 'COOR2', 'PART-1-1', 127), ('COORD', 'COOR2', 'PART-1-1', 128), ('COORD', 'COOR2', 'PART-1-1', 129), ('COORD', 'COOR2', 'PART-1-1', 130), ('COORD', 'COOR2', 'PART-1-1', 131), ('COORD', 'COOR2', 'PART-1-1', 132), ('COORD', 'COOR2', 'PART-1-1', 133), ('COORD', 'COOR2', 'PART-1-1', 134), ('COORD', 'COOR2', 'PART-1-1', 135), ('COORD', 'COOR2', 'PART-1-1', 136), ('COORD', 'COOR2', 'PART-1-1', 137), ('COORD', 'COOR2', 'PART-1-1', 138), ('COORD', 'COOR2', 'PART-1-1', 139), ('COORD', 'COOR2', 'PART-1-1', 140), ('COORD', 'COOR2', 'PART-1-1', 141), ('COORD', 'COOR2', 'PART-1-1', 142), ('COORD', 'COOR2', 'PART-1-1', 143), ('COORD', 'COOR2', 'PART-1-1', 144), ('COORD', 'COOR2', 'PART-1-1', 145), ('COORD', 'COOR2', 'PART-1-1', 146), ('COORD', 'COOR2', 'PART-1-1', 147), ('COORD', 'COOR2', 'PART-1-1', 148), ('COORD', 'COOR2', 'PART-1-1', 149), ('COORD', 

In [53]:
df_times = pd.DataFrame(index = times)
df_times

Empty DataFrame
Columns: []
Index: [(1, 0, 0.0, trans), (1, 1, 1.0, trans), (1, 2, 2.0, trans), (1, 3, 3.0, trans), (1, 4, 4.0, trans), (1, 5, 5.0, trans), (1, 6, 6.0, trans), (1, 7, 7.0, trans), (1, 8, 8.0, trans), (1, 9, 9.0, trans), (1, 10, 10.0, trans), (2, 0, 10.0, final), (2, 1, 10.5, final), (2, 2, 11.0, final), (2, 3, 11.75, final), (2, 4, 12.0, final)]

In [45]:
df_partial

field_name                                               S                 \
component                                              S11
instance_name                                     PART-1-1
idx                                                    1    2    3    4
step_number increment_number total_time step_name
1           0                0.0        trans          0.0  0.0  0.0  0.0

field_name                                                                  \
component
instance_name
idx                                                5    6    7    8    9
step_number increment_number total_time step_name
1           0                0.0        trans      0.0  0.0  0.0  0.0  0.0

field_name                                              ...                \
component                                               ...      S23
instance_name                                           ... PART-1-1
idx                                                10   ...      119  120
step_number increment_number total_time step_name       ...
1           0                0.0        trans      0.0  ...      0.0  0.0

field_name                                                                  \
component
instance_name
idx                                                121  122  123  124  125
step_number increment_number total_time step_name
1           0                0.0        trans      0.0  0.0  0.0  0.0  0.0

field_name
component
instance_name
idx                                                126  127  128
step_number increment_number total_time step_name
1           0                0.0        trans      0.0  0.0  0.0

[1 rows x 768 columns]

In [55]:
df_partial

field_name                                               S                 \
component                                              S11
instance_name                                     PART-1-1
idx                                                    1    2    3    4
step_number increment_number total_time step_name
1           0                0.0        trans          0.0  0.0  0.0  0.0

field_name                                                                  \
component
instance_name
idx                                                5    6    7    8    9
step_number increment_number total_time step_name
1           0                0.0        trans      0.0  0.0  0.0  0.0  0.0

field_name                                              ...                \
component                                               ...      S23
instance_name                                           ... PART-1-1
idx                                                10   ...      119  120
step_number increment_number total_time step_name       ...
1           0                0.0        trans      0.0  ...      0.0  0.0

field_name                                                                  \
component
instance_name
idx                                                121  122  123  124  125
step_number increment_number total_time step_name
1           0                0.0        trans      0.0  0.0  0.0  0.0  0.0

field_name
component
instance_name
idx                                                126  127  128
step_number increment_number total_time step_name
1           0                0.0        trans      0.0  0.0  0.0

[1 rows x 768 columns]

In [61]:
df = pd.DataFrame(index = times, columns = dofs)
df.index.name = 'total_time'

df.columns = pd.MultiIndex.from_tuples(df.columns, names=['field_name', 'component', 'instance_name', 'idx'])
df.index = pd.MultiIndex.from_tuples(df.index, names=[ 'step_number', 'increment_number','total_time', 'step_name', ])

for df_partial in data[field]:
    df = df.merge(df_partial, how = 'left')

KeyboardInterrupt:

step 
frame 
field
block
instance

In [70]:
to_combine = {}
for df in data[field]:
    instance_name = df.columns.get_level_values('instance_name')[0]
    if instance_name not in to_combine:
        to_combine[instance_name] = []
    to_combine[instance_name] += [df,]

for key, value in to_combine.items():
    df = pd.concat(value, axis=0)

# 2. Concatenate them all at once
# This creates the final structure without the overhead of repeated alignment

# 3. Clean up the Index and Column names if they aren't already set
df.columns.names = ['field_name', 'component', 'instance_name', 'idx']
df.index.names = ['step_number', 'increment_number', 'total_time', 'step_name']

df

field_name                                                S            \
component                                               S11
instance_name                                      PART-1-2
idx                                                     1         2
step_number increment_number total_time step_name
1           0                0.00       trans      0.000000  0.000000
            1                1.00       trans      0.000186  0.000318
            2                2.00       trans      0.000373  0.000636
            3                3.00       trans      0.000559  0.000954
            4                4.00       trans      0.000745  0.001272
            5                5.00       trans      0.000932  0.001590
            6                6.00       trans      0.001118  0.001908
            7                7.00       trans      0.001304  0.002226
            8                8.00       trans      0.001491  0.002544
            9                9.00       trans      0.001677  0.002862
            10               10.00      trans      0.001863  0.003180
2           0                10.00      final      0.001863  0.003180
            1                10.50      final      0.001863  0.003180
            2                11.00      final      0.001863  0.003180
            3                11.75      final      0.001863  0.003180
            4                12.00      final      0.001863  0.003180

field_name                                                             \
component
instance_name
idx                                                     3         4
step_number increment_number total_time step_name
1           0                0.00       trans      0.000000  0.000000
            1                1.00       trans      0.000301 -0.000758
            2                2.00       trans      0.000603 -0.001516
            3                3.00       trans      0.000904 -0.002273
            4                4.00       trans      0.001205 -0.003031
            5                5.00       trans      0.001506 -0.003789
            6                6.00       trans      0.001808 -0.004547
            7                7.00       trans      0.002109 -0.005305
            8                8.00       trans      0.002410 -0.006062
            9                9.00       trans      0.002711 -0.006820
            10               10.00      trans      0.003013 -0.007578
2           0                10.00      final      0.003013 -0.007578
            1                10.50      final      0.003013 -0.007578
            2                11.00      final      0.003013 -0.007578
            3                11.75      final      0.003013 -0.007578
            4                12.00      final      0.003013 -0.007578

field_name                                                             \
component
instance_name
idx                                                     5         6
step_number increment_number total_time step_name
1           0                0.00       trans      0.000000  0.000000
            1                1.00       trans     -0.000704 -0.000916
            2                2.00       trans     -0.001409 -0.001832
            3                3.00       trans     -0.002113 -0.002748
            4                4.00       trans     -0.002818 -0.003664
            5                5.00       trans     -0.003522 -0.004579
            6                6.00       trans     -0.004227 -0.005495
            7                7.00       trans     -0.004931 -0.006411
            8                8.00       trans     -0.005635 -0.007327
            9                9.00       trans     -0.006340 -0.008243
            10               10.00      trans     -0.007044 -0.009159
2           0                10.00      final     -0.007044 -0.009159
            1                10.50      final     -0.007044 -0.009159
            2                11.00      final     -0.007044 -0.009159
            3                11.75      final     -0.007044 -0.009159
            4                12.00      final     -0.007044 -0.009159

field_name                                                             \
component
instance_name
idx                                                     7         8
step_number increment_number total_time step_name
1           0                0.00       trans      0.000000  0.000000
            1                1.00       trans     -0.000768  0.000229
            2                2.00       trans     -0.001536  0.000458
            3                3.00       trans     -0.002305  0.000687
            4                4.00       trans     -0.003073  0.000916
            5                5.00       trans     -0.003841  0.001145
            6                6.00       trans     -0.004609  0.001374
            7                7.00       trans     -0.005377  0.001603
            8                8.00       trans     -0.006145  0.001832
            9                9.00       trans     -0.006914  0.002061
            10               10.00      trans     -0.007682  0.002290
2           0                10.00      final     -0.007682  0.002290
            1                10.50      final     -0.007682  0.002290
            2                11.00      final     -0.007682  0.002290
            3                11.75      final     -0.007682  0.002290
            4                12.00      final     -0.007682  0.002290

field_name                                                             ...  \
component                                                              ...
instance_name                                                          ...
idx                                                     9         10   ...
step_number increment_number total_time step_name                      ...
1           0                0.00       trans      0.000000  0.000000  ...
            1                1.00       trans      0.000975  0.000151  ...
            2                2.00       trans      0.001951  0.000302  ...
            3                3.00       trans      0.002926  0.000454  ...
            4                4.00       trans      0.003901  0.000605  ...
            5                5.00       trans      0.004877  0.000756  ...
            6                6.00       trans      0.005852  0.000907  ...
            7                7.00       trans      0.006828  0.001059  ...
            8                8.00       trans      0.007803  0.001210  ...
            9                9.00       trans      0.008778  0.001361  ...
            10               10.00      trans      0.009754  0.001512  ...
2           0                10.00      final      0.009754  0.001512  ...
            1                10.50      final      0.009754  0.001512  ...
            2                11.00      final      0.009754  0.001512  ...
            3                11.75      final      0.009754  0.001512  ...
            4                12.00      final      0.009754  0.001512  ...

field_name                                                             \
component                                               S23
instance_name                                      PART-1-2
idx                                                     119       120
step_number increment_number total_time step_name
1           0                0.00       trans      0.000000  0.000000
            1                1.00       trans      0.002381 -0.004077
            2                2.00       trans      0.004762 -0.008153
            3                3.00       trans      0.007144 -0.012230
            4                4.00       trans      0.009525 -0.016307
            5                5.00       trans      0.011906 -0.020383
            6                6.00       trans      0.014287 -0.024460
            7                7.00       trans      0.016668 -0.028537
            8                8.00       trans      0.019049 -0.032613
            9                9.00       trans      0.021431 -0.036690
            10               10.00      trans      0.023812 -0.040767
2           0                10.00      final      0.023812 -0.040767
            1                10.50      final      0.023812 -0.040767
            2                11.00      final      0.023812 -0.040767
            3                11.75      final      0.023812 -0.040767
            4                12.00      final      0.023812 -0.040767

field_name                                                             \
component
instance_name
idx                                                     121       122
step_number increment_number total_time step_name
1           0                0.00       trans      0.000000  0.000000
            1                1.00       trans      0.002719 -0.010440
            2                2.00       trans      0.005438 -0.020880
            3                3.00       trans      0.008157 -0.031319
            4                4.00       trans      0.010876 -0.041759
            5                5.00       trans      0.013596 -0.052199
            6                6.00       trans      0.016315 -0.062639
            7                7.00       trans      0.019034 -0.073078
            8                8.00       trans      0.021753 -0.083518
            9                9.00       trans      0.024472 -0.093958
            10               10.00      trans      0.027191 -0.104398
2           0                10.00      final      0.027191 -0.104398
            1                10.50      final      0.027191 -0.104398
            2                11.00      final      0.027191 -0.104398
            3                11.75      final      0.027191 -0.104398
            4                12.00      final      0.027191 -0.104398

field_name                                                             \
component
instance_name
idx                                                     123       124
step_number increment_number total_time step_name
1           0                0.00       trans      0.000000  0.000000
            1                1.00       trans     -0.009994 -0.005821
            2                2.00       trans     -0.019988 -0.011641
            3                3.00       trans     -0.029983 -0.017462
            4                4.00       trans     -0.039977 -0.023282
            5                5.00       trans     -0.049971 -0.029103
            6                6.00       trans     -0.059965 -0.034923
            7                7.00       trans     -0.069960 -0.040744
            8                8.00       trans     -0.079954 -0.046565
            9                9.00       trans     -0.089948 -0.052385
            10               10.00      trans     -0.099942 -0.058206
2           0                10.00      final     -0.099942 -0.058206
            1                10.50      final     -0.099942 -0.058206
            2                11.00      final     -0.099942 -0.058206
            3                11.75      final     -0.099942 -0.058206
            4                12.00      final     -0.099942 -0.058206

field_name                                                             \
component
instance_name
idx                                                     125       126
step_number increment_number total_time step_name
1           0                0.00       trans      0.000000  0.000000
            1                1.00       trans      0.011523  0.011880
            2                2.00       trans      0.023046  0.023759
            3                3.00       trans      0.034569  0.035639
            4                4.00       trans      0.046092  0.047519
            5                5.00       trans      0.057615  0.059399
            6                6.00       trans      0.069138  0.071278
            7                7.00       trans      0.080661  0.083158
            8                8.00       trans      0.092184  0.095038
            9                9.00       trans      0.103707  0.106918
            10               10.00      trans      0.115230  0.118797
2           0                10.00      final      0.115230  0.118797
            1                10.50      final      0.115230  0.118797
            2                11.00      final      0.115230  0.118797
            3                11.75      final      0.115230  0.118797
            4                12.00      final      0.115230  0.118797

field_name
component
instance_name
idx                                                     127       128
step_number increment_number total_time step_name
1           0                0.00       trans      0.000000  0.000000
            1                1.00       trans      0.003627  0.004494
            2                2.00       trans      0.007253  0.008988
            3                3.00       trans      0.010880  0.013482
            4                4.00       trans      0.014507  0.017976
            5                5.00       trans      0.018133  0.022471
            6                6.00       trans      0.021760  0.026965
            7                7.00       trans      0.025387  0.031459
            8                8.00       trans      0.029013  0.035953
            9                9.00       trans      0.032640  0.040447
            10               10.00      trans      0.036267  0.044941
2           0                10.00      final      0.036267  0.044941
            1                10.50      final      0.036267  0.044941
            2                11.00      final      0.036267  0.044941
            3                11.75      final      0.036267  0.044941
            4                12.00      final      0.036267  0.044941

[16 rows x 768 columns]

In [79]:
def nested_dict():
    return defaultdict(nested_dict)

def to_standard_dict(d):
    if isinstance(d, defaultdict):
        # Recursively convert the values, then cast the whole thing to a dict
        return {k: to_standard_dict(v) for k, v in d.items()}
    return d

data = nested_dict()
# No KeyErrors, it just builds the path as you go
data['a']['b']['c']['d'] = 'wetewte'
data['a']['c'] = 'wetewte'

data = to_standard_dict(data)
data

{'a': {'b': {'c': {'d': 'wetewte'}}, 'c': 'wetewte'}}